//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellingPoint.Presentation.ClaimAmount {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OCLAIMAMOUNT-NUMBER-OUT", Namespace="http://xmlns.oracle.com/orawsv/WEBSERVICEUSER/GETCLAIMAMOUNT")]
    [System.SerializableAttribute()]
    public partial class OCLAIMAMOUNTNUMBEROUT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.oracle.com/orawsv/WEBSERVICEUSER/GETCLAIMAMOUNT", ConfigurationName="ClaimAmount.GETCLAIMAMOUNTPortType")]
    public interface GETCLAIMAMOUNTPortType {
        
        // CODEGEN: Generating message contract since the wrapper name (GETCLAIMAMOUNTInput) of message GETCLAIMAMOUNTRequest does not match the default value (GETCLAIMAMOUNT)
        [System.ServiceModel.OperationContractAttribute(Action="GETCLAIMAMOUNT", ReplyAction="*")]
        SellingPoint.Presentation.ClaimAmount.GETCLAIMAMOUNTResponse GETCLAIMAMOUNT(SellingPoint.Presentation.ClaimAmount.GETCLAIMAMOUNTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GETCLAIMAMOUNT", ReplyAction="*")]
        System.Threading.Tasks.Task<SellingPoint.Presentation.ClaimAmount.GETCLAIMAMOUNTResponse> GETCLAIMAMOUNTAsync(SellingPoint.Presentation.ClaimAmount.GETCLAIMAMOUNTRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GETCLAIMAMOUNTInput", WrapperNamespace="http://xmlns.oracle.com/orawsv/WEBSERVICEUSER/GETCLAIMAMOUNT", IsWrapped=true)]
    public partial class GETCLAIMAMOUNTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OCLAIMAMOUNT-NUMBER-OUT", Namespace="http://xmlns.oracle.com/orawsv/WEBSERVICEUSER/GETCLAIMAMOUNT", Order=0)]
        public SellingPoint.Presentation.ClaimAmount.OCLAIMAMOUNTNUMBEROUT OCLAIMAMOUNTNUMBEROUT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PPOLICYNO-VARCHAR2-IN", Namespace="http://xmlns.oracle.com/orawsv/WEBSERVICEUSER/GETCLAIMAMOUNT", Order=1)]
        public string PPOLICYNOVARCHAR2IN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PRENEWALCOUNT-NUMBER-IN", Namespace="http://xmlns.oracle.com/orawsv/WEBSERVICEUSER/GETCLAIMAMOUNT", Order=2)]
        public double PRENEWALCOUNTNUMBERIN;
        
        public GETCLAIMAMOUNTRequest() {
        }
        
        public GETCLAIMAMOUNTRequest(SellingPoint.Presentation.ClaimAmount.OCLAIMAMOUNTNUMBEROUT OCLAIMAMOUNTNUMBEROUT, string PPOLICYNOVARCHAR2IN, double PRENEWALCOUNTNUMBERIN) {
            this.OCLAIMAMOUNTNUMBEROUT = OCLAIMAMOUNTNUMBEROUT;
            this.PPOLICYNOVARCHAR2IN = PPOLICYNOVARCHAR2IN;
            this.PRENEWALCOUNTNUMBERIN = PRENEWALCOUNTNUMBERIN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GETCLAIMAMOUNTOutput", WrapperNamespace="http://xmlns.oracle.com/orawsv/WEBSERVICEUSER/GETCLAIMAMOUNT", IsWrapped=true)]
    public partial class GETCLAIMAMOUNTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/orawsv/WEBSERVICEUSER/GETCLAIMAMOUNT", Order=0)]
        public double OCLAIMAMOUNT;
        
        public GETCLAIMAMOUNTResponse() {
        }
        
        public GETCLAIMAMOUNTResponse(double OCLAIMAMOUNT) {
            this.OCLAIMAMOUNT = OCLAIMAMOUNT;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GETCLAIMAMOUNTPortTypeChannel : SellingPoint.Presentation.ClaimAmount.GETCLAIMAMOUNTPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GETCLAIMAMOUNTPortTypeClient : System.ServiceModel.ClientBase<SellingPoint.Presentation.ClaimAmount.GETCLAIMAMOUNTPortType>, SellingPoint.Presentation.ClaimAmount.GETCLAIMAMOUNTPortType {
        
        public GETCLAIMAMOUNTPortTypeClient() {
        }
        
        public GETCLAIMAMOUNTPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GETCLAIMAMOUNTPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GETCLAIMAMOUNTPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GETCLAIMAMOUNTPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SellingPoint.Presentation.ClaimAmount.GETCLAIMAMOUNTResponse SellingPoint.Presentation.ClaimAmount.GETCLAIMAMOUNTPortType.GETCLAIMAMOUNT(SellingPoint.Presentation.ClaimAmount.GETCLAIMAMOUNTRequest request) {
            return base.Channel.GETCLAIMAMOUNT(request);
        }
        
        public double GETCLAIMAMOUNT(SellingPoint.Presentation.ClaimAmount.OCLAIMAMOUNTNUMBEROUT OCLAIMAMOUNTNUMBEROUT, string PPOLICYNOVARCHAR2IN, double PRENEWALCOUNTNUMBERIN) {
            SellingPoint.Presentation.ClaimAmount.GETCLAIMAMOUNTRequest inValue = new SellingPoint.Presentation.ClaimAmount.GETCLAIMAMOUNTRequest();
            inValue.OCLAIMAMOUNTNUMBEROUT = OCLAIMAMOUNTNUMBEROUT;
            inValue.PPOLICYNOVARCHAR2IN = PPOLICYNOVARCHAR2IN;
            inValue.PRENEWALCOUNTNUMBERIN = PRENEWALCOUNTNUMBERIN;
            SellingPoint.Presentation.ClaimAmount.GETCLAIMAMOUNTResponse retVal = ((SellingPoint.Presentation.ClaimAmount.GETCLAIMAMOUNTPortType)(this)).GETCLAIMAMOUNT(inValue);
            return retVal.OCLAIMAMOUNT;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SellingPoint.Presentation.ClaimAmount.GETCLAIMAMOUNTResponse> SellingPoint.Presentation.ClaimAmount.GETCLAIMAMOUNTPortType.GETCLAIMAMOUNTAsync(SellingPoint.Presentation.ClaimAmount.GETCLAIMAMOUNTRequest request) {
            return base.Channel.GETCLAIMAMOUNTAsync(request);
        }
        
        public System.Threading.Tasks.Task<SellingPoint.Presentation.ClaimAmount.GETCLAIMAMOUNTResponse> GETCLAIMAMOUNTAsync(SellingPoint.Presentation.ClaimAmount.OCLAIMAMOUNTNUMBEROUT OCLAIMAMOUNTNUMBEROUT, string PPOLICYNOVARCHAR2IN, double PRENEWALCOUNTNUMBERIN) {
            SellingPoint.Presentation.ClaimAmount.GETCLAIMAMOUNTRequest inValue = new SellingPoint.Presentation.ClaimAmount.GETCLAIMAMOUNTRequest();
            inValue.OCLAIMAMOUNTNUMBEROUT = OCLAIMAMOUNTNUMBEROUT;
            inValue.PPOLICYNOVARCHAR2IN = PPOLICYNOVARCHAR2IN;
            inValue.PRENEWALCOUNTNUMBERIN = PRENEWALCOUNTNUMBERIN;
            return ((SellingPoint.Presentation.ClaimAmount.GETCLAIMAMOUNTPortType)(this)).GETCLAIMAMOUNTAsync(inValue);
        }
    }
}
